In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.linear_model import Lasso
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.inspection import permutation_importance
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import RandomizedSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score

df = pd.read_csv('customer_churn.csv', index_col=0)

In [2]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [3]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   object
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   object
 19  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.1+ MB

In [5]:
X = df.drop(columns=['Churn', 'PhoneService', 'TotalCharges'])

df['Churn'] = df['Churn'].map({
    'Yes': 1,
    'No': 0
})

y = df['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

In [6]:
numerical_cols = ['tenure', 'MonthlyCharges']
categorical_cols = df.drop(columns=['tenure', 'MonthlyCharges', 'PhoneService', 'TotalCharges', 'Churn']).columns.tolist()

In [7]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges        Churn
count    7043.000000  7043.000000     7043.000000  7043.000000
mean        0.162147    32.371149       64.761692     0.265370
std         0.368612    24.559481       30.090047     0.441561
min         0.000000     0.000000       18.250000     0.000000
25%         0.000000     9.000000       35.500000     0.000000
50%         0.000000    29.000000       70.350000     0.000000
75%         0.000000    55.000000       89.850000     1.000000
max         1.000000    72.000000      118.750000     1.000000

In [9]:
# Creating pipeline

# param_grid = {
    
# }

preprocessor = ColumnTransformer(transformers=[
    ('ohe', OneHotEncoder(sparse_output=False, drop='first'), categorical_cols),
    ('scaler', StandardScaler(), numerical_cols),
])


pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('model', XGBClassifier(n_estimators=100, learning_rate=0.3, random_state=42, eval_metric="logloss", verbosity=0))
])

pipe.fit(X_train, y_train)

y_pred = pipe.predict(X_test)
acc_score = accuracy_score(y_test, y_pred)

print(acc_score)
# rs = RandomizedSearchCV(pipe, param_grid, n_iter=20, random_state=42)
# rs.fit(X_train, y_train)

0.7934705464868701

In [19]:
importances = pd.Series(pipe.named_steps['model'].feature_importances_, index=pipe.named_steps['preprocessor'].get_feature_names_out())

print(importances)

ohe__gender_Male                              0.009589
ohe__SeniorCitizen_1                          0.014907
ohe__Partner_Yes                              0.009164
ohe__Dependents_Yes                           0.012265
ohe__MultipleLines_No phone service           0.032455
ohe__MultipleLines_Yes                        0.016685
ohe__InternetService_Fiber optic              0.315263
ohe__InternetService_No                       0.102057
ohe__OnlineSecurity_No internet service       0.000000
ohe__OnlineSecurity_Yes                       0.014877
ohe__OnlineBackup_No internet service         0.000000
ohe__OnlineBackup_Yes                         0.015147
ohe__DeviceProtection_No internet service     0.000000
ohe__DeviceProtection_Yes                     0.010775
ohe__TechSupport_No internet service          0.000000
ohe__TechSupport_Yes                          0.015512
ohe__StreamingTV_No internet service          0.000000
ohe__StreamingTV_Yes                          0.014979
ohe__StreamingMovies_No internet service      0.000000
ohe__StreamingMovies_Yes                      0.028797
ohe__Contract_One year                        0.084146
ohe__Contract_Two year                        0.214720
ohe__PaperlessBilling_Yes                     0.013275
ohe__PaymentMethod_Credit card (automatic)    0.012177
ohe__PaymentMethod_Electronic check           0.015835
ohe__PaymentMethod_Mailed check               0.011716
scaler__tenure                                0.022885
scaler__MonthlyCharges                        0.012771
dtype: float32